on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Builds

jobs:
  build:
    name: Go Build
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - run: git branch
      - run: cat handlers.go
#      - run: go build -ldflags $(GOLDFLAGS) ./...
      - run: go build ./...
